### ISSUE TITLE
color style will replace background-color in some cases

### ISSUE THREAD

**Issue by PatrickSCLin** [gss/engine#155]
in GSS 2.0

#box {
    background-color: green;
    color: blue;
}

background-color will be blue, but it should be green.

#box {
    color: blue;
    background-color: green;
}

it works fine.

**Comment by paulyoung** [comment]
@Inviz - I think the next step here would be to add both of these as example specs in https://github.com/gss/engine/blob/master/spec/end-to-end.coffee

**Comment by Inviz** [comment]
Yeah, css dumping is really fragile... Thanks for report, this is amusing.

**Comment by Inviz** [comment]
Fixed on 2.1.x branch. Thank you very much.

The problem was of course substring matching. When it assigned "color" property, it tried to find "color:" substring which matched "background-color:". I made it care about the preceeding characte.

https://github.com/gss/engine/commit/9e845cba63ee664416bce28f51dbc07e9390c527
