### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Dublerq** [gss/engine#216]
I haven't seen much activity in this project for months or even years. Travis checking is also broken. Is this still alive? I'm just wondering if it's worth to use it somewhere else than hello world test website.

**Comment by Inviz** [comment]
It's dead in the sense of progress, and it's dead in terms of usage too. I think the experiment proven itself not worthy - it's too heavy for regular sites. The company that developed it used it as a publication step, exporting final css, but that turned out to be kinda brittle. Most of runtime overhead is due to stateful nature of cassowary solver. Changing constraint set causes solved values to "stick", so gss does a bunch of work to handle and bring it closer to unachievable level of statelessness of CSS.

You still can use it (clone gss/document, npm link gss/engine optionally, npm install, and grunt build it), but you have to understand why you do it. If it's about layout, just go with flexbox.
